### ISSUE TITLE
Solve user config sparse/full issue

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/extension-aiSwapper#3]
Not sure if this issue actually belongs in the UCP3-GUI repo or here. Since using the custom menu is crucial for creating the issue, I listed it here.

> as soon as i add ANY plugin even AI related ones, the swapper looses all stuff that was not added via the menu
but only, if i previously added anything via the Aiswappers custom menu

https://discord.com/channels/426318193603117057/1230981973028110336

**Comment by Krarilotus** [comment]
short summary to reporduce bug

to reproduce the bug (apply after each step if you want to follow along how the config is changed):
1. add any ai pack (e.g. Apex-AI-Applied)
2. go to AI-Swapper menu under customization tab, and change something (e.g. put Caliph Behaviour on the rat).
3. add any other plugin under the contents tab
-> Outcome: All of the changes from the ai pack (Apex-AI-Applied) are gone.
-> The AI Menu still shows all the Apex AIs and your changes
-> But they are lost when checkign the config.
